karelapan/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('apps.sitio.urls')),
    url(r'^api/', include('apps.api.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^karelecatl/', include('apps.karelecatl.urls')),
    url(r'^material/', include('apps.libro.urls')),
    url(r'^channel.html', 'apps.sitio.views.channel'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^404/$', 'apps.sitio.views.error404'),
        url(r'^403/$', 'apps.sitio.views.error403'),
        url(r'^500/$', 'apps.sitio.views.error500'),
    )

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar

    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/evaluador/models.py
# -*- coding:utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from tinymce.models import HTMLField
import json
import os
import datetime

def valida_mundos(str_mundo):
    """valida que 'str_mundo' sea un documento JSON que representa un
    mundo válido de karel"""
    try:
        mundo = json.loads(str_mundo)
    except ValueError:
        raise ValidationError('No pude leer este mundo como json')
    else:
        if 'karel' in mundo and 'casillas' in mundo and 'dimensiones' in mundo:
            if 'posicion' in mundo['karel'] and 'orientacion' in mundo['karel'] and 'mochila' in mundo['karel']:
                if type(mundo['karel']['posicion']) == list and mundo['karel']['orientacion'] in ['norte', 'sur', 'este', 'oeste'] and type(mundo['karel']['mochila'])==int and type(mundo['casillas']) == list:
                    if 0<mundo['dimensiones']['filas']<=100 and 0<mundo['dimensiones']['columnas']<=100 and mundo['karel']['mochila']>=-1:
                        bueno = True
                        for casilla in mundo['casillas']:
                            if 'fila' in casilla and 'columna' in casilla and 'paredes' in casilla and 'zumbadores' in casilla:
                                if type(casilla['fila'])==int and type(casilla['columna'])==int and type(casilla['zumbadores'])==int and type(casilla['paredes']) == list:
                                    if 0<casilla['fila']<=100 and 0<casilla['columna']<=100 and casilla['zumbadores']>=-1:
                                        bparedes = True
                                        for pared in casilla['paredes']:
                                            if pared not in ['norte', 'sur', 'este', 'oeste']:
                                                bparedes = False
                                                break
                                        if not bparedes:
                                            raise ValidationError('Valor inválido para pared')
                                    else:
                                        bueno = False
                                        break
                                else:
                                    bueno = False
                                    break
                            else:
                                bueno = False
                                break
                        if not bueno:
                            raise ValidationError('Error en una de las casillas')
                    else:
                        raise ValidationError('Las dimensiones sobrepasan lo permitido')
                else:
                    raise ValidationError('El tipo de dato de una llave no coincide')
            else:
                raise ValidationError('Este mundo no tiene una de las llaves posicion, orientación o mochila')
        else:
            raise ValidationError('Este mundo no contiene las llaves principales de karel, mundo y casillas')

def url_casos_evaluacion(problema, nombre_original_archivo):
    """Obtiene el nombre que tendrá el archivo de un set de casos de
    evaluación"""
    return 'casos/'+problema.nombre_administrativo+'.nkec'

def valida_json(cadena):
    """identifica si la cadena es json"""
    try:
        json.loads(cadena)
    except:
        raise ValidationError('No es un json valido')

class Nivel(models.Model):
    """Los problemas del evaluador están agrupados en estos niveles para
    su mejor desarrollo con los usuarios"""
    nombre      = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField()
    nivel       = models.IntegerField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'niveles'
        ordering            = ['nivel']


class Problema(models.Model):
    """Un problema del evaluador o de un concurso para resolverse con
    karel"""
    nombre                  = models.CharField(max_length=140, unique=True)
    nombre_administrativo   = models.CharField(max_length=140, unique=True)
    descripcion             = HTMLField()
    problema                = HTMLField()
    agradecimiento          = models.TextField(blank=True)
    veces_resuelto          = models.IntegerField(default=0)
    veces_intentado         = models.IntegerField(default=0)
    mejor_tiempo            = models.IntegerField(default=-1)
    autor                   = models.ForeignKey(User)
    fecha_publicacion       = models.DateField(auto_now_add=True)
    nivel                   = models.ForeignKey(Nivel)
    publico                 = models.BooleanField(default=True)
    futuro                  = models.BooleanField(default=False)
    logica_fuerte           = models.BooleanField(default=False)
    limite_recursion        = models.IntegerField(default=65000)
    limite_iteracion        = models.IntegerField(default=65000)
    limite_ejecucion        = models.IntegerField(default=200000)
    mundo                   = models.TextField(validators=[valida_mundos])
    mundo_resuelto          = models.TextField(validators=[valida_mundos])
    casos_de_evaluacion     = models.FileField(upload_to=url_casos_evaluacion)

    def __unicode__(self):
        return self.nombre

    def es_reciente(self):
        """Un problema es reciente durante 15 días después de su publicación"""
        publicacion = datetime.datetime(self.fecha_publicacion.year, self.fecha_publicacion.month, self.fecha_publicacion.day, tzinfo=timezone.now().tzinfo)
        return publicacion >= (timezone.now() - datetime.timedelta(days=15))

    class Meta:
        ordering = ['nombre']


class Consideracion(models.Model):
    """Cada problema de karel tiene consideraciones que limitan el mundo
    """
    problema    = models.ForeignKey(Problema, related_name='consideraciones')
    texto       = models.CharField(max_length=300)

    def __unicode__(self):
        return self.texto

    class Meta:
        verbose_name_plural = 'consideraciones'


class Concurso(models.Model):
    """Los usuarios pueden concursar y sacar puntajes independientes en
    este tipo de concursos"""
    fecha_inicio        = models.DateTimeField()
    fecha_fin           = models.DateTimeField()
    nombre              = models.CharField(max_length=140)
    descripcion         = models.TextField()
    activo              = models.BooleanField(default=True)
    problemas           = models.ManyToManyField(Problema, blank=True)
    grupos              = models.ManyToManyField('usuarios.Grupo', related_name='concursos')
    administradores     = models.ForeignKey('auth.Group', related_name='+')
    olimpiada           = models.ForeignKey('usuarios.Olimpiada', blank=True, null=True)
    duracion_preguntas  = models.IntegerField(default=90, help_text="La duración en minutos del periodo en que pueden hacer preguntas los concursantes a partir del inicio del concurso")
    ranking_publico     = models.BooleanField(default=False)
    importante          = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre

    def puntaje_total(self):
        return 100*self.problemas.count()

    def ranking(self):
        usuarios = []
        for participacion in Participacion.objects.filter(concurso=self).order_by('-puntaje')[:5]:
            usuario = participacion.usuario
            usuario.score = participacion.puntaje
            usuarios.append(usuario)
        return usuarios

    def lista_grupos(self):
        return ', '.join([str(g) for g in self.grupos.all()])

    class Meta:
        permissions = (
            ("puede_ver_ranking", "Puede ver ranking"),
            ("administrar_todos_concursos", "Puede administrar todos los concursos"),
        )
        ordering    = ['-fecha_inicio']


class Participacion(models.Model):
    """Maneja la participación de un usuario en un concurso"""
    usuario         = models.ForeignKey(User, related_name='participaciones')
    concurso        = models.ForeignKey(Concurso, related_name='participaciones')
    puntaje         = models.IntegerField(default=0)
    hora_entrada    = models.DateTimeField(auto_now_add=True)
    primera_ip      = models.IPAddressField()

    class Meta:
        verbose_name_plural = 'participaciones'
        unique_together = ("usuario", "concurso")


class Envio(models.Model):
    """Describe un envío que se va a la cola de evaluación"""
    usuario             = models.ForeignKey(User, related_name='envios')
    problema            = models.ForeignKey(Problema, related_name='+')
    hora                = models.DateTimeField(auto_now_add=True)
    estatus             = models.CharField(max_length=1, choices=(
        ('E', 'Evaluado'),
        ('P', 'Pendiente de evaluacion'),
        ('S', 'En evaluación')
    ), default='P')
    puntaje             = models.IntegerField(default=0)
    codigo              = models.TextField(blank=True, null=True)
    codigo_archivo      = models.CharField(max_length=140)
    tiempo_ejecucion    = models.IntegerField(default=0)
    resultado           = models.CharField(max_length=17, choices=(
        ('OK', 'Ok'),
        ('ERROR_COMPILACION', 'Error de compilación'),
        ('CASOS_INCOMPLETOS', 'Casos incompletos')
    ), default='OK')
    mensaje             = models.CharField(max_length=250, blank=True)
    concurso            = models.ForeignKey(Concurso, null=True, blank=True, related_name='envios')
    ip                  = models.IPAddressField(blank=True, null=True, default='0.0.0.0')
    casos               = models.TextField(validators=[valida_json], blank=True)

    def lee_casos(self):
        class Caso:
            def __init__(self, puntos_obtenidos, mensaje, puntos_valor, terminacion):
                self.puntos_obtenidos = puntos_obtenidos
                self.mensaje = mensaje
                self.puntos_valor = puntos_valor

apps/usuarios/forms.py
# -*- coding:utf-8 -*-
from django import forms
from apps.usuarios.models import Perfil, Grupo, Usuario
from django.core.exceptions import ValidationError
import re

def valida_nombre_de_usuario(cadena):
    caracteres = 'qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890@.-_+'
    for i in cadena:
        if i not in caracteres:
            raise ValidationError('Caracter no válido')
    try:
        u = Usuario.objects.get(username=cadena)
        raise ValidationError('Este nombre de usuario ya está en uso')
    except Usuario.DoesNotExist:
        pass

def valida_correo(cadena):
    try:
        u = Usuario.objects.get(email=cadena)
        raise ValidationError('Este correo electrónico ya está en uso')
    except Usuario.DoesNotExist:
        pass
    m = re.match('[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}', cadena)
    if m:
        a, b = m.span()
        if b != len(cadena):
            raise ValidationError('No es un correo válido')
    else:
        raise ValidationError('No es un correo válido')

class PerfilForm(forms.ModelForm):
    required_css_class = 'required'
    nombre_asesor       = forms.CharField(required=False)
    asesor              = forms.CharField(widget=forms.HiddenInput, required=False)
    class Meta:
        model = Perfil
        exclude = ('usuario', 'grupos', 'problemas_resueltos', 'puntaje', 'sexo', 'fecha_nacimiento', 'ultima_omi', 'inscripciones', 'nombre_completo', 'asesor', 'confirm_token')

class RegistroForm(forms.ModelForm):
    correo              = forms.EmailField(validators=[valida_correo])
    nombre_asesor       = forms.CharField(required=False)
    nombre_de_usuario   = forms.CharField(validators=[valida_nombre_de_usuario])
    contrasenia         = forms.CharField(widget=forms.PasswordInput, label="Contraseña")
    repetir_contrasenia = forms.CharField(widget=forms.PasswordInput, label="Repetir contraseña")
    asesor              = forms.CharField(widget=forms.HiddenInput, required=False)
    required_css_class = 'required'
    class Meta:
        model = Perfil
        exclude = ('usuario', 'problemas_resueltos', 'puntaje', 'grupos', 'nombre_completo', 'asesor', 'inscripciones', 'confirm_token')

apps/usuarios/views.py
# Create your views here.

templates/ayuda.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} Ayuda {% endblock %}
{% block contenido %}
  <div class="span6">
    <div class="well">
      <h3>Preguntas frecuentes</h3>
      <p>En esta sección encontrarás respuestas a preguntas muy comunes sobre este evaluador. Si tienes dudas también puedes preguntar</p>
      <p style="text-align:center;">
        <a href="/faqs" class="btn btn-large btn-primary">Entrar</a>
      </p>
    </div>
</div>
<div class="span6">
  <div class="well">
    <h3>Wiki</h3>
    <p>Consulta la documentación existente sobre karel, karelapan y otros proyectos relacionados.</p>
    <p style="text-align:center;">
      <a href="/wiki" class="btn btn-large btn-primary">Entrar</a>
    </p>
  </div>
</div>
{% endblock %}

templates/base.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} Inicio {% endblock %}
{% block contenido %}
  <div class="span12">
    <h1>Esta es una vista</h1>
  </div>
{% endblock %}

templates/concurso.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} {{ concurso }} {% endblock %}
{% block contenido %}
  <div class="span3"></div>
  <div class="span6">
    <h4>
      {{ concurso }}
      {% if concurso.ranking_publico %}
        <small><a href="{% url 'apps.sitio.views.concurso_ver_ranking_publico' concurso.id %}">ranking</a></small>
      {% endif %}
    </h4>
    <p>{{ concurso.descripcion }}</p>
    <p class="lead">Quedan {{ concurso.quedan_dias }}{{ concurso.quedan_horas }}{{ concurso.quedan_minutos }}{{ concurso.quedan_segundos }}</p>
    <h4>Problemas</h4>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Problema</th>
          <th>Tu puntaje</th>
        </tr>
      </thead>
        {% for problema in concurso.lista_problemas %}
          <tr>
            <td>
              <a href="{% url 'apps.sitio.views.problema_concurso' concurso.id problema.id %}">{{ problema }}</a>
            </td>
            <td>
              {% autoescape off %}
                {{ problema.mejor_puntaje_usuario }}
              {% endautoescape %}
            </td>
          </tr>
        {% endfor %}
      <tbody>
      </tbody>
    </table>
  </div>
  <div class="span3"></div>
{% endblock %}

templates/consultas.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} Consultas {% endblock %}
{% block contenido %}
  <div class="span12">
    <h3>Preguntas que hacen los usuarios en el concurso <em>{{ concurso }}</em></h3>
    <input type="hidden" id="id_concurso" value="{{ concurso.id }}">
    <div id="consultas-admin">
      <div class="consulta">
        <form id="aclaracion-general" method="post">
          <h5>
            Hacer aclaración general para el problema:
            <select name="problema">
              {% for problema in concurso.problemas.all %}
                <option value="{{ problema.id }}">{{ problema }}</option>
              {% endfor %}
            </select>
            <input type="hidden" name="concurso" value="{{ concurso.id }}"><br>
            <textarea name="respuesta" class="input-xxlarge" placeholder="Detalle de la aclaración"></textarea>
            <input type="submit" value="Enviar" class="btn btn-info">
            <input type="reset" id="reset-aclaracion" style="display:none;">
          </h5>
        </form>
      </div>
      <div id="mensajes" class="alert" style="display:none;"></div>
      {% for consulta in consultas %}
        {% if consulta.leido and not consulta.descartado %}
          <div class="consulta">
            <input type="hidden" class="consulta-id" value="{{ consulta.id }}">
            <h5>{{ consulta.mensaje }} <span class="muted">Problema: {{ consulta.problema }}, Usuario: {{ consulta.usuario }}</span> {{ consulta.hora }}</h5> {{ consulta.respuesta }}
          </div>
        {% else %}{% if consulta.descartado %}
          <div class="consulta-bad">
            <input type="hidden" class="consulta-id" value="{{ consulta.id }}">
            <h5>{{ consulta.mensaje }} <span class="muted">Problema: {{ consulta.problema }}, Usuario: {{ consulta.usuario }}</span> {{ consulta.hora }}</h5> <span class="text-error">Rechazada</span>
          </div>
        {% else %}
          <div class="consulta-bad">
            <input type="hidden" class="consulta-id" value="{{ consulta.id }}">
            <h5>{{ consulta.mensaje }} <span class="muted">Problema: {{ consulta.problema }}, Usuario: {{ consulta.usuario }}</span> {{ consulta.hora }}</h5>
            <form class="responde-consulta" method="post" onsubmit="return envia_respuesta(this);">
              <div class="components">
                <textarea class="input-xxlarge" rows="3" name="respuesta"></textarea>
                <input type="hidden" name="consulta" value="{{ consulta.id }}">
                <input type="hidden" name="rechazar" class="rechazar-hidden">
                <input type="submit" value="Enviar" class="btn">
                <input type="button" value="Rechazar" class="rechazar-consulta btn btn-danger" onclick="rechaza_respuesta(this);">
              </div>
            </form>
          </div>
        {% endif %}{% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/envios.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} Envíos {% endblock %}
{% block contenido %}
  <div class="span12">
    <h3>Problemas enviados por los usuarios <small><a href="{% url 'apps.sitio.views.mis_soluciones_view' %}">Ver s&oacute;lo las m&iacute;as</a></small></h3>
    <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Usuario</th>
            <th>Problema</th>
            <th>Puntos</th>
            <th>Tiempo Ejecuci&oacute;n</th>
            <th>Terminaci&oacute;n/Mensaje</th>
            <th>Hora</th>
          </tr>
        </thead>
        <tbody>
        {% for envio in envios %}
          <tr class="{% ifnotequal envio.estatus 'E' %}info{% else %}{% ifequal envio.resultado 'OK' %}success{% endifequal %}{% ifequal envio.resultado 'CASOS_INCOMPLETOS' %}warning caso-incompleto{% endifequal %}{% ifequal envio.resultado 'ERROR_COMPILACION' %}error{% endifequal %}{% endifnotequal %}">
            <td>{% ifequal envio.estatus 'E' %}<i class="icon-ok" title="Código evaluado"></i>{% else %}{% ifequal envio.estatus 'P' %}<i class="icon-pause" title="Pendiente de evaluación"></i>{% else %}<i class="icon-eye-open" title="Código en evaluación"></i>{% endifequal %}{% endifequal %}</td>
            <td><a href="{% url 'apps.sitio.views.usuario_view' envio.usuario.username %}" class="preventpropagation">{{ envio.usuario.username }}</a></td>
            <td><a href="{% url 'apps.sitio.views.problema_detalle' envio.problema.nombre_administrativo %}" class="preventpropagation">{{ envio.problema }}</a></td>
            <td>{% ifequal envio.estatus 'E' %}{{ envio.puntaje }}{% endifequal %}</td>
            <td>{% ifequal envio.estatus 'E' %}{{ envio.tiempo_ejecucion }}{% endifequal %}</td>
            <td>
              {% ifequal envio.estatus 'E' %}<a href="#" class="casos-evaluacion">{{ envio.resultado }}</a> {{ envio.mensaje }}
                {% if envio.resultado == 'CASOS_INCOMPLETOS' or envio.resultado == 'OK' %}
                  <table class="table tabla-casos" style="display:none;">
                    <thead>
                      <tr>
                        <td>Caso</td>
                        <td>Puntos</td>
                        <td>Terminación</td>
                        <td>Mensaje</td>
                      </tr>
                    </thead>
                    <tbody>
                      {% for caso in envio.lee_casos %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ caso.puntos_obtenidos }}</td>
                          <td>{{ caso.terminacion }}</td>
                          <td>{{ caso.mensaje }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                {% endif %}
              {% else %}
                <a class="btn casos-pendiente"><i class="icon-remove"></i></a>
              {% endifequal %}
            </td>
            <td>{{ envio.hora }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    <div class="pagination pagination-centered">
      <ul>
        <li><a href="{% url 'apps.sitio.views.envios_view' %}">Últimos</a></li>
        {% if envios.has_previous %}
          <li><a href="{% url 'apps.sitio.views.envios_view' %}?pagina={{ envios.previous_page_number }}">Más recientes</a></li>
        {% else %}
          <li class="disabled"><a>Más recientes</a></li>
        {% endif %}
        <li class="active"><a>{{ envios.number }}</a></li>
        {% if envios.has_next %}
          <li><a href="{% url 'apps.sitio.views.envios_view' %}?pagina={{ envios.next_page_number }}">Más viejos</a></li>
        {% else %}
          <li class="disabled"><a>Más viejos</a></li>
        {% endif %}
        <li><a href="{% url 'apps.sitio.views.envios_view' %}?pagina={{ envios.paginator.num_pages }}">Primeros</a></li>
      </ul>
    </div>
  </div>
{% endblock %}

templates/medallero.html
{% extends 'template.html' %}
{% load staticfiles bootstrap_tags sekizai_tags %}
{% block titulo %} Medallero {% endblock %}
{% block contenido %}
  {% addtoblock 'js' %}
    <script type="text/javascript" language="javascript" src="{% static 'js/medallero.js' %}"></script>
  {% endaddtoblock %}
  <div class="span8">
    <h2>Medallero <small>Lo mejor de lo mejor</small></h2>
    <p class="muted"><em>Concursos para la olimpiada en curso</em></p>
    {% for concurso in concursos %}
      <h3>{{ concurso }} <small>{{ concurso.fecha_inicio }} [<a href="{% url 'apps.sitio.views.concurso_ver_ranking_publico' concurso.id %}">ver ranking completo</a>]</small></h3>
      <table class="table">
        <thead>
          <tr>
            <th style="width:20px;">#</th>
            <th style="width:200px;">Nombre</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          {% for usuario in concurso.ranking %}
            <tr>
              <td>
                <strong>{{ forloop.counter }}</strong>
              </td>
              <td>
                <a href="{% url 'apps.sitio.views.usuario_view' usuario.username %}"><img src="{{ usuario.perfil.gravatar_pequenio }}"> {{ usuario.perfil.nombre_completo }}</a>
              </td>
              <td>
                {% progressbar usuario.score concurso.puntaje_total %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% empty %}
      <div class="well">
        <h4>Aun no ha ocurrido ningún concurso</h4>
      </div>
    {% endfor %}
  </div>
  <div class="span4">
    <h4>Puntajes globales en karelapan <small><a href="">Ver todos</a></small></h4>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Lugar</th>
          <th>Nombre</th>
          <th>Puntaje</th>
        </tr>
      </thead>
      <tbody>
        {% for usuario in usuarios %}
          <tr>
            <td><strong>{{ forloop.counter }}</strong></td>
            <td>
              <a href="{% url 'apps.sitio.views.usuario_view' usuario.username %}"><img src="{{ usuario.gravatar_pequenio }}"> {{ usuario }}</a>
            </td>
            <td>{{ usuario.perfil.puntaje }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="3"><strong>No hay usuarios inscritos a la olimpiada actual</strong></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/problemas.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} Problemas {% endblock %}
{% block contenido %}
  <div class="span12">
    <h4>&iexcl;A programar!</h4>
    <p>Aqu&iacute; encontrar&aacute;s una interesante lista de problemas. No pierdas ni un segundo y dev&oacute;rala de pies a cabeza, te est&aacute;n esperando ansiosos por que los resuelvas.</p>
    <p><strong>¿Quieres aprender el lenguaje primero? <a href="/wiki">entra aquí</a></strong></p>
    <div class="row">
      <div class="span3"></div>
      <div class="span6">
        <h3 style="text-align:center;">Lista de problemas</h3>
        {% for nivel in niveles %}
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th colspan="{% if user.is_authenticated %}5{% else %}4{% endif %}" style="text-align:center;">
                  <p class="lead">{{ nivel.nombre }}</p>
                  <small>{{ nivel.descripcion }}</small>
                </th>
              </tr>
              <tr>
                <th>Problema</th>
                <th><abbr title="Veces">V.</abbr> Resuelto</th>
                <th><abbr title="Veces">V.</abbr> Intentado</th>
                <th>Mejor tiempo</th>
                {% if user.is_authenticated %}
                  <th>T&uacute;</th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
              {% for problema in nivel.problemas %}
                <tr>
                  <td>
                    <a href="/problema/{{ problema.nombre_administrativo }}">{{ problema.nombre }}</a>
                    {% if problema.es_reciente %}
                      <span class="badge pull-right">nuevo!</span>
                    {% endif %}
                  </td>
                  <td>{{ problema.veces_resuelto }}</td>
                  <td>{{ problema.veces_intentado }}</td>
                  <td>{% ifequal problema.mejor_tiempo -1 %}---{% else %}{{ problema.mejor_tiempo }}{% endifequal %}</td>
                  {% if user.is_authenticated %}
                    <td>
                      {% autoescape off %}
                        {{ problema.mejor_puntaje_usuario }}
                      {% endautoescape %}
                    </td>
                  {% endif %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endfor %}
      </div>
      <div class="span3"></div>
    </div>
  </div>
{% endblock %}

templates/ranking.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titulo %} {{ concurso }} {% endblock %}
{% block contenido %}
  <div class="span12">
    <h3>Ranking para el concurso <em>{{ concurso }}</em></h3>
    <h5><a href="{% url 'apps.sitio.views.concursos_view' %}">Volver</a> <span class="muted">|</span> <a href="{% url 'apps.api.views.ranking_csv' concurso.id %}">descargar CSV</a></h5>
    <table class="table table-stripped">
      <thead>
        <tr>
          <th>Lugar</th>
          <th>Nombre</th>
          <th>Puntos</th>
          {% for problema in concurso.problemas.all %}
            <th>{{ problema }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for usuario in usuarios %}
          <tr>
            <td><strong>{{ forloop.counter }}.</strong></td>
            <td><a href="{% url 'apps.sitio.views.usuario_view' usuario.username %}">{{ usuario.perfil.nombre_completo }}</a></td>
            <td>
              {{ usuario.score }}
            </td>
            {% for resultado in usuario.resultados %}
              <td>
                {% autoescape off %}
                  {{ resultado }}
                {% endautoescape %}
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}